name: AntiCreeperDestroy
version: '1.1.0'
main: org.mcfurina.antiCreeperDestroy.AntiCreeperDestroy
api-version: '26.1.2'
authors: [ MCFurina ]
description: A simple Minecraft plugin that prevents creepers from destroying blocks and dropped items, but still retains the explosion effect and damage to players.
folia-supported: true